// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredikceVytěžováníFVE.Data;

#nullable disable

namespace PredikceVytěžováníFVE.Migrations
{
    [DbContext(typeof(FVEDbContext))]
    [Migration("20250312193947_update mqtt")]
    partial class updatemqtt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.MqttData", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double>("Charge")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "ToBAT");

                    b.Property<double>("Consumed_T")
                        .HasColumnType("REAL");

                    b.Property<double>("Consumption")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "Consumed");

                    b.Property<double>("Discharge")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "FromBAT");

                    b.Property<double>("Feed")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "BUY");

                    b.Property<double>("FromBAT_T")
                        .HasColumnType("REAL");

                    b.Property<double>("Input")
                        .HasColumnType("REAL");

                    b.Property<double>("Load")
                        .HasColumnType("REAL");

                    b.Property<double>("Output")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "SELL");

                    b.Property<double>("PRICE_CZK")
                        .HasColumnType("REAL");

                    b.Property<double>("PVenergy")
                        .HasColumnType("REAL");

                    b.Property<double>("PVenergy_T")
                        .HasColumnType("REAL");

                    b.Property<int>("P_Batt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "P_BAT");

                    b.Property<int>("P_Grid")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "P_GRID");

                    b.Property<int>("P_HOME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_Inv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_OffGr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_OnGr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_PV")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SELL_T")
                        .HasColumnType("REAL");

                    b.Property<int>("SoC")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temp24h")
                        .HasColumnType("REAL");

                    b.Property<double>("Temp48h")
                        .HasColumnType("REAL");

                    b.Property<int>("ToBAT_T")
                        .HasColumnType("INTEGER");

                    b.Property<double>("consPredict")
                        .HasColumnType("REAL");

                    b.HasKey("Date", "Time");

                    b.ToTable("mqttData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.TimeChartData<double>", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Date", "Time");

                    b.ToTable("spotData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.TimeChartData<int>", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date", "Time");

                    b.ToTable("forecastData");
                });
#pragma warning restore 612, 618
        }
    }
}
