// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredikceVytěžováníFVE.Data;

#nullable disable

namespace PredikceVytěžováníFVE.Migrations
{
    [DbContext(typeof(FVEDbContext))]
    [Migration("20250226161701_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.MqttBo", b =>
                {
                    b.Property<string>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Charge")
                        .HasColumnType("REAL");

                    b.Property<double>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<double>("Discharge")
                        .HasColumnType("REAL");

                    b.Property<double>("Feed")
                        .HasColumnType("REAL");

                    b.Property<double>("Input")
                        .HasColumnType("REAL");

                    b.Property<double>("Load")
                        .HasColumnType("REAL");

                    b.Property<double>("Output")
                        .HasColumnType("REAL");

                    b.Property<double>("PVenergy")
                        .HasColumnType("REAL");

                    b.Property<int>("P_Batt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_Grid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_Inv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_OffGr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_OnGr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_PV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoC")
                        .HasColumnType("INTEGER");

                    b.HasKey("DateTime");

                    b.ToTable("mqttBos");
                });
#pragma warning restore 612, 618
        }
    }
}
