// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredikceVytěžováníFVE.Data;

#nullable disable

namespace PredikceVytěžováníFVE.Migrations
{
    [DbContext(typeof(FVEDbContext))]
    [Migration("20260320100019_Add consumption forecast2")]
    partial class Addconsumptionforecast2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.ConsumptionForecastBo", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("index");

                    b.Property<decimal?>("Forecast")
                        .HasColumnType("TEXT")
                        .HasColumnName("forecast");

                    b.HasKey("TimeStamp");

                    b.ToTable("ConsumptionForecastData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.ForecastSolarBo", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeStamp");

                    b.ToTable("ForecastSolarData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.HourlyBo", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("P_HOME")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeStamp");

                    b.ToTable("HourlyData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.PvForecastBo", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeStamp");

                    b.ToTable("PvForecastData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.SpotBo", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("DateTime");

                    b.ToTable("SpotData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.WeatherForecastBo", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeStamp");

                    b.ToTable("WeatherForecastData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.MqttData", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BUY")
                        .HasColumnType("REAL");

                    b.Property<double?>("BUY_T")
                        .HasColumnType("REAL");

                    b.Property<double?>("Charge")
                        .HasColumnType("REAL");

                    b.Property<double?>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Discharge")
                        .HasColumnType("REAL");

                    b.Property<double?>("Feed")
                        .HasColumnType("REAL");

                    b.Property<double?>("FromBAT")
                        .HasColumnType("REAL");

                    b.Property<double?>("FromBAT_T")
                        .HasColumnType("REAL");

                    b.Property<string>("FullMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GRID_LIMIT")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Input")
                        .HasColumnType("REAL");

                    b.Property<double?>("Load")
                        .HasColumnType("REAL");

                    b.Property<double?>("Output")
                        .HasColumnType("REAL");

                    b.Property<double?>("PRICE_CZK")
                        .HasColumnType("REAL");

                    b.Property<double?>("PVenergy")
                        .HasColumnType("REAL");

                    b.Property<double?>("PVenergy_T")
                        .HasColumnType("REAL");

                    b.Property<int?>("P_BAT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_Batt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("P_EPS")
                        .HasColumnType("REAL");

                    b.Property<int?>("P_GRID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_GRID_L1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_GRID_L2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_GRID_L3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_HOME")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_HOME_L1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_HOME_L2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_HOME_L3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_Inv")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_OffGr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_OnGr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_PV")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SELL")
                        .HasColumnType("REAL");

                    b.Property<double?>("SELL_T")
                        .HasColumnType("REAL");

                    b.Property<int?>("SoC")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ToBAT")
                        .HasColumnType("REAL");

                    b.Property<double?>("ToBAT_T")
                        .HasColumnType("REAL");

                    b.HasKey("Date", "Time");

                    b.ToTable("MqttData");
                });
#pragma warning restore 612, 618
        }
    }
}
