// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PredikceVytěžováníFVE.Data;

#nullable disable

namespace PredikceVytěžováníFVE.Migrations
{
    [DbContext(typeof(FVEDbContext))]
    partial class FVEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PredikceVytěžováníFVE.Data.testData", b =>
                {
                    b.Property<DateTime>("dateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("dateTime");

                    b.ToTable("testData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.MqttDataBto", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("BUY")
                        .HasColumnType("REAL");

                    b.Property<double>("BUY_T")
                        .HasColumnType("REAL");

                    b.Property<double>("Consumed")
                        .HasColumnType("REAL");

                    b.Property<double>("Consumed_T")
                        .HasColumnType("REAL");

                    b.Property<double>("FromBAT")
                        .HasColumnType("REAL");

                    b.Property<double>("FromBAT_T")
                        .HasColumnType("REAL");

                    b.Property<double>("PRICE_CZK")
                        .HasColumnType("REAL");

                    b.Property<double>("PVForecast")
                        .HasColumnType("REAL");

                    b.Property<double>("PVenergy")
                        .HasColumnType("REAL");

                    b.Property<double>("PVenergy_T")
                        .HasColumnType("REAL");

                    b.Property<int>("P_BAT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_EPS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_GRID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_HOME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P_PV")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SELL")
                        .HasColumnType("REAL");

                    b.Property<double>("SELL_T")
                        .HasColumnType("REAL");

                    b.Property<int>("SoC")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temp24h")
                        .HasColumnType("REAL");

                    b.Property<double>("Temp48h")
                        .HasColumnType("REAL");

                    b.Property<double>("ToBAT")
                        .HasColumnType("REAL");

                    b.Property<double>("ToBAT_T")
                        .HasColumnType("REAL");

                    b.Property<double>("consPredict")
                        .HasColumnType("REAL");

                    b.HasKey("TimeStamp");

                    b.ToTable("mqttData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.TimeChartData<double>", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("TimeStamp");

                    b.ToTable("spotData");
                });

            modelBuilder.Entity("PredikceVytěžováníFVE.Models.DB.TimeChartData<int>", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeStamp");

                    b.ToTable("forecastData");
                });
#pragma warning restore 612, 618
        }
    }
}
